### ISSUE TITLE
Missed file in models directory

### ISSUE THREAD

**Issue by GolferChen** [BAI-Yeqi/SF2F_PyTorch#4]
Hello, thanks for the code again. I found many files that are imported in `models/__init__.py` are missed, e.g., `.face_gan`, leading to many dependency errors when running `train.py`. Would you please check on the model files? Many thanks.

**Comment by BAI-Yeqi** [comment]
@GolferChen Hi man, thank you for pointing this out. The aforementioned `FaceGan` is actually located in `models/face_decoders.py`. Actually, the open-source version of `models/__init__.py` is a bit outdated. You can checkout `models/model_setup.py` to see which modules in `models/__init__.py` are actually needed and delete the redundant parts. 

Since I am currently on vacation and have limited access to my computing clusters. As it is, would you please fix the issue above, and send me a pull request if it is convenient for you?

Thank you for your kind help.

**Comment by GolferChen** [comment]
Hello, @BAI-Yeqi, I have uncommented the useless import in `models/`. Now it works now. Please check the pull request.

**Comment by BAI-Yeqi** [comment]
@GolferChen Good evening, I have merged the aforementioned pull request and removed redundant comments.

If this repo is currently working fine on your machine, would you like to close this issue? Thank you~
